contact/urls.py
from django.urls import path, reverse_lazy
from . import views
from .models import Contact


urlpatterns = [
    path('contacts', views.ContactList.as_view(), name='contact_list'),
    path('detail/<int:pk>', views.ContactDetail.as_view(), name='contact_detail'),
    path('create', views.ContactCreate.as_view(model=Contact, success_url=reverse_lazy('contact_list')), name='contact_create'),
    path('update/<int:pk>', views.ContactUpdate.as_view(model=Contact, success_url=reverse_lazy('contact_list')), name='contact_update'),
    path('delete/<int:pk>', views.ContactDelete.as_view(model=Contact, success_url=reverse_lazy('contact_list')), name='contact_delete'),
    path('profile/<int:pk>', views.profile_page, name="profile_page")
]

core/urls.py
from django.urls import path
from . import views



urlpatterns = [
	path('employees/', views.emp_list, name="emp_list"),
	path('employees/create/', views.emp_create, name="emp_create"),
	path('employees/delete/<int:id>', views.emp_delete, name="empdelete"),
	path('employees/view/<int:id>', views.emp_detail, name="emp_detail"),
	path('employees/update/<int:id>', views.emp_update, name="emp_update"),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include("core.urls")),
    path('crud/', include("crud.urls")),
    path('contact/', include("contact.urls")),
    path('accounts/', include('userregister.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

userregister/urls.py
from django.contrib.auth import views
from django.urls import path, include, re_path, reverse_lazy

from . import views
from django.contrib.auth import views as auth_views

from django.views.generic import RedirectView

app_name = 'userregister'

urlpatterns = [
    path('register/', views.register, name='register'),

    path('login/', views.login_user, name='login_user'),

    path('logout/', views.logout_user, name='logout_user'),

]

contact/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
	name = models.CharField(max_length=50)
	email = models.EmailField()
	address = models.CharField(max_length=250)
	contactno = models.IntegerField()

contact/forms.py
from .models import *
from django import forms
from django.forms import ModelForm




class ContactCreateForm(ModelForm):

	class Meta:
		model = Contact
		fields = ('name', 'email', 'address', 'contactno')


	def clean(self):
		cleaned_data = super(ContactCreateForm, self).clean()
		contactno = cleaned_data.get('contactno')
		if len(str(contactno))!=10:
			self.add_error(None, forms.ValidationError('contact no should have 10 digits'))
		return cleaned_data

contact/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from django.views.generic.edit import UpdateView, CreateView, DeleteView
from .models import Contact

from .forms import ContactCreateForm
from django.contrib.messages.views import SuccessMessageMixin

from django.contrib.auth.views import LoginView
from django.contrib.auth.models import User


class ContactLoginView(LoginView):
    template_name = "contact/login.html"
    redirect_authenticated_user = True

class ContactList(ListView):
	model = Contact

class ContactDetail(DetailView):
	model = Contact

class ContactCreate(SuccessMessageMixin, CreateView):
	model = Contact
	form_class = ContactCreateForm
	success_message = 'Form has been successfully submitted!'

class ContactDelete(DeleteView):
	model = Contact
	# fields = '__all__'

class ContactUpdate(UpdateView):
	model = Contact
	form_class = ContactCreateForm

def profile_page(request, pk):
    user = Contact.objects.get(id = pk)
    return render(request, 'contact/user_profile.html', {'user_profile': user})

contact/templates/contact/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'contact/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> -->

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'contact/css/profile.css' %}">
    <link href="{% static 'contact/css/dashboard.css' %}" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Mojave</a>
      <div style="padding-left:700px;">
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      </div>
      <div>
        <a class="fa fa-user" style="color:white;" href="{% url 'profile_page' user.id %}">  {{user.username}}</a>
      </div>
      <ul class="navbar-nav px-3">
         
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="{% url 'userregister:logout_user' %}">Sign out</a>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'emp_list' %}">
                  <span data-feather="home"></span>
                  Core
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'product_list' %}">
                  <span data-feather="file"></span>
                  CRUD
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'contact_list' %}">
                  <span data-feather="shopping-cart"></span>
                  Contact
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <!-- <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2">Dashboard</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                This week
              </button>
            </div>
          </div> -->


          <div>
                {% block content %}
                
                {% endblock %}
            </div>
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="{% static 'contact/js/popper.min.js' %}"></script>
    <script src="{% static 'contact/js/bootstrap.min.js' %}"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
  </body>
</html>

contact/templates/contact/contact_confirm_delete.html
<h1>Contact Delete?</h1>
<form method="post">
	{% csrf_token %}
	Are You Sure You want to delete this Contact?
	<input type="submit" value="Submit">
</form>

contact/templates/contact/contact_detail.html
<h1>Contact Detail</h1>

	<p>{{object.name}}</p>
	<p>{{object.email}}</p>
	<p>{{object.address}}</p>
	<p>{{object.contactno}}</p>

contact/templates/contact/contact_form.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

<h1>Enter Contacts</h1>
<section style="width:25%; padding-left: 25px;">
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input class="btn btn-primary" type="submit" value="Submit">
</form>
</section>

contact/templates/contact/contact_list.html
{% extends 'contact/base.html' %}
{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}








<div class="panel panel-default panel-table">
		<div class="panel-heading">
		  <div class="row">
			<div class="col col-xs-6">
			  <h3 class="panel-title">Contact List</h3>
			</div>
			<div class="col col-xs-6 text-right">
			  <a  href="{% url 'contact_create' %}" class="btn btn-sm btn-primary ">Create New</a>
			</div>
		  </div>
		</div>
		<div class="panel-body">


				<table class="table table-striped table-bordered table-list">
						<thead>
							<tr>		
								<th>Name</th>
								<th>Email</th>
								<th>Address</th>
								<th>Contact No.</th>
								<th>Detail</th>
								<th>Update</th>
								<th>Delete</th>
							</tr>
						</thead>
						<tbody>
							{% for contact in object_list %}
							<tr>
								<td>{{contact.name}}</td>
								<td>{{contact.email}}</td>
								<td>{{contact.address}}</td>
								<td>{{contact.contactno}}</td>
								<td align="center">
									<a  href="{% url "contact_detail"  contact.id  %}"><i class="fas fa-eye fa-lg"></i></a>
								</td>
								<td align="center">	
									<a  href="{% url "contact_update"  contact.id  %}"><i class="fas fa-pencil-alt fa-lg"></i></a>
								</td>
								<td align="center">
									<a  href="{% url "contact_delete"  contact.id  %}"><i class="fas fa-trash fa-lg"></i></a>
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
</div>
</div>













{% endblock %}

contact/templates/contact/user_profile.html
    {% extends 'contact/base.html' %}
    {% block content %}

    <div class="container emp-profile">
                <form method="post">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="profile-img" style="padding-right: 100px;">
                                <img src="https://iisy.fi/wp-content/uploads/2018/08/profiledefault.png" style="height:275; width:250;" alt="profile image"/>
                                
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="profile-head">
                                        <h5>
                                            {{user.username}}
                                        </h5>
                                        <h6>
                                            Web Developer and Designer
                                        </h6>
                                        <p class="proile-rating">RANKINGS : <span>8/10</span></p>
                                <ul class="nav nav-tabs" id="myTab" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#" role="tab" aria-controls="home" aria-selected="true">About</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <input type="submit" class="profile-edit-btn" name="btnAddMore" value="Edit Profile"/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="profile-work">
                                <p>WORK LINK</p>
                                <a href="">Website Link</a><br/>
                                <a href="">Bootsnipp Profile</a><br/>
                                <a href="">Bootply Profile</a>
                                <p>SKILLS</p>
                                <a href="">Web Designer</a><br/>
                                <a href="">Web Developer</a><br/>
                                <a href="">WordPress</a><br/>
                                <a href="">WooCommerce</a><br/>
                                <a href="">PHP, .Net</a><br/>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="tab-content profile-tab" id="myTabContent">
                                <div class="tab-pane fade show active" role="tabpanel" aria-labelledby="home-tab">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <label>User Id</label>
                                                </div>
                                                <div class="col-md-6">
                                                    <p>{{user.id}}</p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <label>First Name</label>
                                                </div>
                                                <div class="col-md-6">
                                                    <p>{{user.first_name}}</p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                    <div class="col-md-6">
                                                        <label>Last Name</label>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <p>{{user.last_name}}</p>
                                                    </div>
                                                </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <label>Email</label>
                                                </div>
                                                <div class="col-md-6">
                                                    <p>{{user.email}}</p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <label>Phone</label>
                                                </div>
                                                <div class="col-md-6">
                                                    <p>123 456 7890</p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <label>Profession</label>
                                                </div>
                                                <div class="col-md-6">
                                                    <p>Web Developer and Designer</p>
                                                </div>
                                            </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>           
            </div>
    {% endblock %}